Update log messages to indicate fast/slow path
vmware/concord-bft pull request #1413
Opened 2021-04-27 07:05 UTC by shgandhi

This commit updates log messages to include commit path, this is to
allow easy debugging without having to correlate a specific protocol
with the commit path being used. This commit also converts certain
DEBUG log messages to INFO type. This closes BC-7983.

2021-04-27 09:44 UTC, teoparvanov requested changes
Hi Shruti, thanks for attempting a fix. However, I wouldn't suggest making those logs INFO, as they will pollute the log output. We are already looking for ways to reduce the overall log size.

CC: @HristoStaykov

2021-04-27 09:44 UTC, teoparvanov commented on bftengine/src/bftengine/ReplicaImp.cpp
> +                                                           << ", commit path: " << CommitPathToStr(pp->firstPath()));
I think this will flood the logs... It should remain at DEBUG level IMO.

2021-04-27 09:44 UTC, teoparvanov commented on bftengine/src/bftengine/ReplicaImp.cpp
> +                                                        << ", commit path: " << CommitPathToStr(pp->firstPath()));
same here, should be DEBUG

2021-04-27 14:28 UTC, shgandhi commented
Thanks for the review @teoparvanov, updated the PR as per your comments.

2021-04-28 11:08 UTC, HristoStaykov approved these changes
LGTM, thanks @shgandhi for the added thorough information on the Commit paths.

2021-04-28 16:03 UTC, teoparvanov approved these changes
LGTM, thanks Shruti!

2021-04-28 17:56 UTC, merged