Add apollo tests for unwedge
vmware/concord-bft pull request #1714
Opened 2021-07-22 10:18 UTC by nkgeorgiev

Add tests for:
state transfer after unwedge
unwedge with n-f replicas
wedge status command

2021-07-23 13:16 UTC, yontyon requested changes
Overall it looks very good
I have only one small comment about using an already existed method for getting the wedge status
Thanks!

2021-07-23 13:16 UTC, yontyon commented on tests/apollo/test_skvbc_reconfiguration.py
> +        with trio.fail_after(seconds=90):
Use https://github.com/vmware/concord-bft/blob/c54bc03d1783d8734fdfef2a449528e0da10b961/tests/apollo/test_skvbc_reconfiguration.py#L1718 instead

2021-07-23 13:16 UTC, yontyon commented on tests/apollo/test_skvbc_reconfiguration.py
> +        with trio.fail_after(seconds=60):
same

2021-07-23 13:16 UTC, yontyon commented on tests/apollo/test_skvbc_reconfiguration.py
> +        with trio.fail_after(seconds=90):
Here we can also use the method from above (but it needed to be changed a bit)

2021-07-23 13:16 UTC, yontyon commented on tests/apollo/test_skvbc_reconfiguration.py
> +        with trio.fail_after(seconds=90):
same

2021-07-23 13:16 UTC, yontyon commented on tests/apollo/test_skvbc_reconfiguration.py
> +        with trio.fail_after(seconds=90):
same

2021-08-04 13:23 UTC, teoparvanov approved these changes
Looks great, thanks!!

2021-08-04 13:37 UTC, yontyon approved these changes
LGTM!
Thanks

2021-08-04 13:51 UTC, merged