Enable test_create_dbcheckpoint_with_parallel_client_requests
vmware/concord-bft pull request #2635
Opened 2022-05-18 10:17 UTC by agrkushvm

Problem Overview
test_create_dbcheckpoint_with_parallel_client_requests tescase of skvbc_dbsnapshot was failing. So Enabled the testcase in this PR as fix for it was added : https://github.com/vmware/concord-bft/pull/2252

Testing Done
Ran the test case multiple times to verify the stability.

2022-05-18 14:02 UTC, teoparvanov requested changes
Locking the master branch until made stable.

2022-06-22 09:28 UTC, nkumar04 approved these changes
LGTM!

2022-07-26 04:36 UTC, nityavasudevan commented
How many runs were done locally and on CI?

2022-07-26 05:45 UTC, nityavasudevan commented
Please update teh testing section based on the runs

2022-07-27 17:17 UTC, agrkushvm commented
=== Starting iteration 47/100

    Start 153: skvbc_dbsnapshot_tests
    
    1/1 Test #153: skvbc_dbsnapshot_tests ...........   Passed  418.96 sec

The following tests passed:
	skvbc_dbsnapshot_tests

100% tests passed, 0 tests failed out of 1

2022-07-28 05:57 UTC, nityavasudevan approved these changes

2022-07-28 06:01 UTC, teoparvanov approved these changes
Thanks, approved.

2022-07-28 06:06 UTC, merged