Enable delay strategy in state transfer apollo test
vmware/concord-bft pull request #2697
Opened 2022-06-23 16:55 UTC by mdarade

Enable delay strategy for fetcher-sender-crash test so that
test gets enough time to catch replica in state transfer.

* **Problem Overview**  
State transfer test crashing fetcher and sender node was sometimes failing to catch them in state transfer. We have now increased number of checkpoints and also delaying messages so that test gets enough time to crash both the nodes.
* **Testing Done**  
Ran tests locally 50+ times matching CI config.

2022-06-23 22:02 UTC, glevkovich requested changes

2022-06-23 22:02 UTC, glevkovich commented on tests/apollo/test_skvbc_checkpoints.py
> -    @unittest.skip("Unstable test")
Why did you enable only a single test?
Maybe I misunderstood you.
We have 4 tests disabled by @StefanPalashev  recently. See:
60e1b8a716f8a8553367059ee4a9de2dccce7dc6
"Disable unstable checkpoint tests"

2022-06-27 10:29 UTC, glevkovich approved these changes
LGTM

2022-06-27 10:36 UTC, eyalrund approved these changes

2022-06-27 10:37 UTC, merged