Move reconfiguration lib to libs
vmware/concord-bft pull request #2962
Opened 2023-03-16 13:07 UTC by yontyon

* **Problem Overview**  
  As part of the open source strategy, this PR moves the reconfiguration library to libs
* **Testing Done**  
  CI

2023-03-16 13:20 UTC, eyalrund approved these changes

2023-03-16 13:40 UTC, toly-kournik commented on libs/reconfiguration/CMakeLists.txt
> +project (libreconfiguration LANGUAGES CXX)
can you `git mv` this file for history tracking

2023-03-16 15:01 UTC, teoparvanov commented
@yontyon, IMHO this change looks risky at this late stage in the release (and not functionally needed for 1.9 either). Also, wouldn't there be any related changes in GitLab (f.e. due to the moving of header files to different directories)?

2023-03-16 15:41 UTC, teoparvanov requested changes
In addition, I'd suggest to talk to @harsht1737 to make sure all the reconfiguration tests have been re-enabled in post-master before proceeding with this change.

2023-03-16 15:52 UTC, toly-kournik commented
> @yontyon, IMHO this PR looks risky at such a late stage in the release (and not functionally needed for 1.9 either). Also, wouldn't there be any related changes in GitLab (f.e. because header files are moving to different directories)?

@teoparvanov , there's no risk as no new functionality is added, we are just arranging the code in a new way.

2023-03-16 15:53 UTC, toly-kournik commented
> @yontyon, IMHO this PR looks risky at such a late stage in the release (and not functionally needed for 1.9 either). Also, wouldn't there be any related changes in GitLab (f.e. because header files are moving to different directories)?

The includes were already prefixed by the containing folder name, i.e `#include "reconfiguration/*`

2023-03-16 16:04 UTC, toly-kournik commented
> Thanks for clarifying, Toly! Ideally though we would wait for the 1.9 branch to be pulled (mid next week I expect). I'd also suggest to manually run all Hermes reconfiguration tests on a private build - even the ones that are currently disabled temporarily.

Basically it can wait for the next week

2023-03-23 08:47 UTC, teoparvanov approved these changes
Approving this PR, as the 1.9/Beta2 release has been postponed. Thanks for the patience @yontyon and @toly-kournik !

2023-03-27 10:28 UTC, merged