Add click to intall_deps.sh
vmware/concord-bft pull request #998
Opened 2020-10-29 17:43 UTC by oded282

Click is a Python package for command-line interfaces. As part of building a CLI tool to parse Concord's logs, I use Click to implement the infrastructure for the parsing tool.

Additionally, reconfigured locale settings for two reasons:
1. Required for Click usage.
2. Solves the error that occurs when trying to use eliot-tree from within a docker container.

2020-10-29 19:25 UTC, f-squirrel requested changes
Please change the commit summary to `Docker update to version 1.0` and put all the details in the commit message.

2020-11-03 22:35 UTC, andrewjstone requested changes
This shouldn't be a 1.0 version. It should be version 0.10. We are not ready to call the build 1.0 IMO.

2020-11-03 22:35 UTC, andrewjstone commented on Dockerfile
> +ENV LANG=C.UTF-8
Nit: missing newline

2020-11-04 10:27 UTC, f-squirrel commented
> This shouldn't be a 1.0 version. It should be version 0.10. We are not ready to call the build 1.0 IMO.

Good point, Andrew!

2020-11-06 21:38 UTC, robem requested changes

2020-11-06 21:38 UTC, robem commented on Makefile
> +CONCORD_BFT_DOCKER_IMAGE_VERSION:=1.0
Andrew mentioned this but I'm marking it explicitly. Our docker image should probably stay below 1.0 as long as concord-bft isn't 1.0. `0.10` should work.

2020-11-10 14:20 UTC, closed without merging